class Game:
    def __init__(self):
        self.appid =
        self.name =
        self.developer =
        self.release_date =
        self.genres =
        self.steamspy_tags =
        self.positive_ratings =
        self.negative_ratings =
        self.average_playtime =
        self.median_playtime =
        self.owners =
        self.price =